### ISSUE TITLE
TypeError on "WRIGHT"

### ISSUE THREAD

**Issue by serapio** [Zack--/phonetics#3]
The logic for `process_G` returns `None` for the sequence "WRIGHT" (and "RIGH", "LIGHT", etc).
```
<L117>
        else:
            if (idx > 2 and s.get(idx - 1) == 'U' and
               s.get(idx - 3) in {'C', 'G', 'L', 'R', 'T'}):
                return ('F',  'F', 2)
            elif idx > 0 and s.get(idx - 1) != 'I':
                return ('K',  'K', 2)
```
It looks like it should `return ('', '', 2)`.

**Comment by ZackDibe** [comment]
Fixed on `master` and released in [`v1.0.5`](https://pypi.python.org/pypi/phonetics/1.0.5). Thank you.
